name: '$(Build.BuildId)'
variables:
  - name: BUILD_CONFIGURATION
    value: 'Release'

  - name: FUNCTION_PUBLISH_DIRECTORY
    value: '$(Build.SourcesDirectory)/function-app'

  - name: FUNCTION_DIRECTORY
    value: '$(Build.SourcesDirectory)/src/Realtime.Presenter.Function'
  
  - name: ARCHIVED_FUNCTION_PATH
    value: '$(Build.ArtifactStagingDirectory)/Realtime.Presenter.Function.$(Build.BuildId).zip'

  - name: WEB_DIRECTORY
    value: '$(Build.SourcesDirectory)/src/Realtime.Presenter.Web'

  - name: WEB_PUBLISH_DIRECTORY
    value: '$(Build.SourcesDirectory)/src/Realtime.Presenter.Web/dist'
  
  - name: WEB_ARTIFACTS_DIRECTORY
    value: '$(Build.ArtifactStagingDirectory)/website'
  
  - name: FUNCTION_TESTS_DIRECTORY
    value: '$(Build.SourcesDirectory)/tests/Realtime.Presenter.Function.Tests'

  - name: MOBILE_TESTS_DIRECTORY
    value: '$(Build.SourcesDirectory)/tests/Realtime.Presenter.Mobile.Tests'
  
jobs:
- job: CI
  displayName: CI
  pool: 
    vmImage: 'macOS-10.14'
  workspace:
    clean: all
  steps:
  - task: NuGetToolInstaller@0
    displayName: Install NuGet

  - task: NodeTool@0
    displayName: Install Node 10
    inputs:
      versionSpec: '10.x'

  - bash: npm install --global yarn
    displayName: Install Yarn

  - task: NuGetCommand@2
    displayName: Restore NuGet Packages
    inputs:
      restoreSolution: '**/*.sln'

  - bash: yarn
    displayName: Install Node Packages
    workingDirectory: '$(WEB_DIRECTORY)'

  - task: DotNetCoreCLI@2
    displayName: Function Tests
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'
      workingDirectory: '$(FUNCTION_TESTS_DIRECTORY)'
      
  - task: DotNetCoreCLI@2
    displayName: Forms Tests
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'
      workingDirectory: '$(MOBILE_TESTS_DIRECTORY)'

  - bash: yarn test
    displayName: Web Tests
    workingDirectory: '$(WEB_DIRECTORY)'

  - task: DotNetCoreCLI@2
    displayName: Publish Function
    inputs:
      command: 'publish'
      arguments: '--output $(FUNCTION_PUBLISH_DIRECTORY)'
      configuration: '$(BUILD_CONFIGURATION)'
      publishWebProjects: false
      workingDirectory: '$(FUNCTION_DIRECTORY)'
  
  - bash: yarn build
    displayName: Publish Website
    workingDirectory: '$(WEB_DIRECTORY)'
  
  - task: ArchiveFiles@2
    displayName: Package Function
    inputs:
      rootFolderOrFile: '$(FUNCTION_PUBLISH_DIRECTORY)'
      includeRootFolder: false
      archiveFile: '$(ARCHIVED_FUNCTION_PATH)'

  - task: CopyFiles@2
    displayName: Copy Website
    inputs:
      sourceFolder: '$(WEB_PUBLISH_DIRECTORY)'
      targetFolder: '$(WEB_ARTIFACTS_DIRECTORY)'

  - task: AzureCLI@1
    displayName: Deploy Function App
    inputs:
      azureSubscription: 'Azure VS Pro Subscription'
      scriptLocation: 'scriptPath'
      scriptPath: './deploy-app.sh'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure VS Pro Subscription'
      appType: 'functionApp'
      WebAppName: 'realtime-app-func'
      packageForLinux: '$(ARCHIVED_FUNCTION_PATH)'
      enableCustomDeployment: true
      DeploymentType: 'webDeploy'
      TakeAppOfflineFlag: true
      RemoveAdditionalFilesFlag: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts