name: '$(Build.BuildId)'
variables:
  BUILD_CONFIGURATION: 'Release'
  PUBLISH_DIRECTORY: '$(Build.SourcesDirectory)/function-app'
  FUNCTION_DIRECTORY: '$(Build.SourcesDirectory)/src/Realtime.Presenter.Function'
  FUNCTION_TESTS_DIRECTORY: '$(Build.SourcesDirectory)/tests/Realtime.Presenter.Function.Tests'
  MOBILE_TESTS_DIRECTORY: '$(Build.SourcesDirectory)/tests/Realtime.Presenter.Mobile.Tests'
  ARCHIVED_FUNCTION_PATH: '$(Build.ArtifactStagingDirectory)/Realtime.Presenter.Function'
jobs:
- job: Build
  displayName: Build $(Build.BuildId)
  pool: 
    vmImage: 'macOS-10.14'
  workspace:
    clean: all
  steps:
  - task: NuGetToolInstaller@0
    displayName: Install NuGet

  - task: NuGetCommand@2
    displayName: Restore NuGet Packages
    inputs:
      restoreSolution: '**/*.sln'
      
  - task: DotNetCoreCLI@2
    displayName: Function Tests
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'
      arguments: '--logger trx'
      workingDirectory: '$(FUNCTION_TESTS_DIRECTORY)'
      
  - task: DotNetCoreCLI@2
    displayName: Forms Tests
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'
      arguments: '--logger trx'
      workingDirectory: '$(MOBILE_TESTS_DIRECTORY)'
      
  - task: DotNetCoreCLI@2
    displayName: Publish Function
    inputs:
      command: 'publish'
      arguments: '--output $(PUBLISH_DIRECTORY)'
      configuration: '$(BUILD_CONFIGURATION)'
      publishWebProjects: true
      workingDirectory: '$(FUNCTION_DIRECTORY)'
  
  - task: ArchiveFiles@2
    displayName: Package Function
    inputs:
      rootFolderOrFile: '$(PUBLISH_DIRECTORY)'
      includeRootFolder: false
      archiveFile: '$(ARCHIVED_FUNCTION_PATH)'
      
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts