name: '$(Build.BuildId)'
variables:
  BUILD_CONFIGURATION: 'Release'
  PUBLISH_DIRECTORY: '$(Build.SourcesDirectory)/function-app'
  FUNCTION_DIRECTORY: '$(Build.SourcesDirectory)/src/Realtime.Presenter.Function'
  ARCHIVED_FUNCTION_PATH: '$(Build.ArtifactStagingDirectory)/Realtime.Presenter.Function'
jobs:
- job: Build
  pool: 
    vmImage: 'macOS-10.14'
  workspace:
    clean: all
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'
      arguments: '--logger trx'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--output $(PUBLISH_DIRECTORY)'
      configuration: '$(BUILD_CONFIGURATION)'
      publishWebProjects: true
      workingDirectory: '$(FUNCTION_DIRECTORY)'
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(PUBLISH_DIRECTORY)'
      includeRootFolder: false
      archiveFile: '$(ARCHIVED_FUNCTION_PATH)'
      
  - task: PublishBuildArtifacts@1